# Generated by Django 5.0.3 on 2024-04-27 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(null=True, upload_to='image')),
                ('product_description', models.TextField(null=True)),
                ('product_price', models.IntegerField()),
                ('product_stock', models.IntegerField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categorymodel')),
            ],
        ),
    ]
