# Generated by Django 5.0.3 on 2024-04-29 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Productmodel',
        ),
    ]
